version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: leilao/leilao_flask:1.0.0
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:1204@flask_db:5432/leilao
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1204
      - POSTGRES_USER=postgres
      - POSTGRES_DB=leilao
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: {}
    